language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.3.1

install:
  - gem uninstall bundler
  - gem install bundler --version '1.17.3'

script:
    - bundle install
    - bundle exec rake spec