name: Publish

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    name: Publish gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Create and push Git tag
        uses: duderman/gh-gem-tag-action@v1
        id: release_info
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
      - uses: marvinpinto/actions@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.release_info.outputs.tag }}
          files: |
            danger-pmd-${{ steps.release_info.outputs.tag }}.gem
